### ISSUE TITLE
[rfe] color docs for tire temperature

### ISSUE THREAD

**Issue by thoraxe** [s-victor/TinyPedal#14]
Hi there,

This is not a bug report but more of an enhancement request. I don't really understand how the `*_color_surface` values are supposed to work for coloring the tire temperature.

My settings are the defaults of:
```
        "font_color_surface": "#000000",
        "bkg_color_surface": "#222222",
```

But `#000000` and `#222222` are nearly black. The display is definitely not black.

Mostly the tire spends time between red (cold) and yellow (hotter) which makes no sense.

I'd like to mimic the rFactor2 native style color temperature behavior where blue is cold and orange/white is completely overheated. There's basically no color/visual difference right now between normal operating temperature (~145F) and "burning up hot" (210F+). Maybe this is a bug with C versus F?

Any tips here?

**Comment by s-victor** [comment]
Hi, thanks for reporting. You are correct, it is a mistake where color assignment happens after C to F conversion, so F value does not match the heatmap range using C unit. I'll fix this asap.

**Comment by s-victor** [comment]
Hi, the issue should be fixed now https://github.com/s-victor/TinyPedal/commit/1fbc3e5b2e40bd5e3ad7b312671f9fbab4f71193
Lemme know if any further problems, thanks!
