### ISSUE TITLE
New tire pressure/load widget isn't in Wiki

### ISSUE THREAD

**Issue by thoraxe** [s-victor/TinyPedal#2]
Does the Wiki just come from docs/customization.md? Because if so I can probably submit a PR for adding the doc.

**Comment by s-victor** [comment]
Yes, it is exact copy of customization.md (easier to maintain this way I think). And the Pressure/load widget is under `Pressure` section in customization.md, you can add any missing info to this section, thanks.

**Comment by thoraxe** [comment]
Whoops, I didn't see it somehow. My bad!

Seems like you're doing a good job so far!
