### ISSUE TITLE
[RFE] restore "pit limiter" warning on gear (Speed) widget

### ISSUE THREAD

**Issue by thoraxe** [s-victor/TinyPedal#24]
It seems that with 2.0.2 there is no longer a "PIT LIMIT" warning on the gear/speed indicator.  This was the "speed limiter text" option in TP1.

TP2 only has this in the "flags" widget, which I tend to keep off to the side. 

It would be really nice to have the speed limiter function back in the gear widget.

Alternatively, you could make the limiter widget its own completely separate thing, which would allow you to size and put it anywhere you wanted.

TP2 is otherwise awesome. Thank you SO much for the effort you put into it!

**Comment by s-victor** [comment]
Thanks for the feedback. While rewritten 2.0, it was one thing that doesn't fit the new code at the time, so it was left behind. I should be able to bring it back, will see.

**Comment by s-victor** [comment]
hi, speed limiter indicator is restored in today release.
