### ISSUE TITLE
[Feature / Suggestion] - Add track corner names 

### ISSUE THREAD

**Issue by srlemke** [s-victor/TinyPedal#26]
Hello,
If you are running out of ideas for new feature, here goes a suggestion:

A few years ago I created for ACC, using simhub, a widget that displayed track corner names:
https://www.racedepartment.com/downloads/live-track-corner-names-shows-all-corner-names-on-all-acc-tracks.38078/

The corner names I got here: https://www.racingcircuits.info
The 'hard' work part it to map the corners to the correct point.

At that point I basically had another widget displaying the % of the track I was, dunno if rF2 shared memory has that info, I would believe so, so basically, when I was withing a range of track % my widget shows the corner name.

An idea would be to have some small extra widget/module that would display the track % traveled and let the users input the corner name and probably store it to some local file(like where the classes and heatmap files are) or file per track id. The advantage of this would that this files would be shareable and could be added/merged upstream.

I believe it could fit well in the existing track map widget, like this:

![TP](https://github.com/s-victor/TinyPedal/assets/1301954/463cd92c-7afb-43e7-b2a9-9363e323e2a5)

thanks!

**Comment by s-victor** [comment]
Hi, the corner name feature is now implemented in the track notes editor & track notes widget in v2.20.0 update, see forum post for details: https://forum.studio-397.com/index.php?threads/tinypedal-open-source-overlay-app-for-rf2-radar-pedal-ffb-deltabest-relative-fuel-calculator.71557/page-41#post-1147514

Have fun
