### ISSUE TITLE
[Enhancement] Little tweak on driver name

### ISSUE THREAD

**Issue by srlemke** [s-victor/TinyPedal#27]
Hello!
It's me again to annoy :)

![Screenshot_2023-05-27_01-01-32](https://github.com/s-victor/TinyPedal/assets/1301954/58294fed-a047-41c9-8fd4-042662e2fabd)

I think the default 'print' of the driver name when the option to also show the car name becomes a little overwhelming (a lot of chars packed together), in order to improve that I did that little tweak in the code and the result is in the screenshot above, do you think that could be implemented?

I'm not creating a pull request because I do not really develop in python as you will see in the diff bellow:

```
diff --git a/tinypedal/widget/relative.py b/tinypedal/widget/relative.py
index 90ab8b1..8512ed5 100644
--- a/tinypedal/widget/relative.py
+++ b/tinypedal/widget/relative.py
@@ -21,7 +21,6 @@ Relative Widget
 """
 
 import random
-
 from PySide2.QtCore import Qt, Slot
 from PySide2.QtGui import QFont, QFontMetrics
 from PySide2.QtWidgets import (
@@ -456,7 +455,7 @@ class Draw(Widget):
         elif self.wcfg["driver_name_mode"] == 1:
             text = name[1]  # vehicle name
         elif name[1]:
-            text = f"{name[0]} [{name[1]}]"  # combined name
+            text = f"{name[0] : <25} {name[1]}"  # combined name
         else:
             text = ""
         if self.wcfg["driver_name_uppercase"]:
```
But I think you will get the idea :)

(the hard-coded '25' is the chars for driver name only, so currently in the settings I have 55.
(maybe when the user selects driver name ' 2' - combined, he could also have the option to set the 'car name length' )
and something like this:
+            text = f"{name[0] : <$driver_name_length} {name[1] $car_name_length}"  # combined name

thanks!

**Comment by s-victor** [comment]
Hi, great suggestion. I'll add your code shortly. Also if you don't mind, I would add your name to the contributor list, lemme know, thanks.

**Comment by srlemke** [comment]
Hello, you certainly can add me to the contributor list if you believe it's a  fit.

The new implementation is really great!
There seems to a small bug with the option:

`Font Color Vehicle name`

As changing the color in the GUI does not apply on the widget.
I did not mind going into the code to find the exact issue as I believe that is probably trivial fix.

![image](https://github.com/s-victor/TinyPedal/assets/1301954/fa5efb07-9b82-48bb-9101-1166f60934ae)

**Comment by s-victor** [comment]
Hi, no problem. I have just tested and all working here. If you are looking at changing the background color for your row, it is the `bkg_color_player_vehicle_name` option does that. Option without `player` keyword is for non-player vehicles.

![test1](https://github.com/s-victor/TinyPedal/assets/21177177/dae28980-114e-4ec9-8d8f-03765e86e558)

**Comment by s-victor** [comment]
Hi, no problem.

The `Font Color XXXX` is mostly a placeholder, because this font color from all non-player vehicles is used by `show_lap_difference` option, which overrides this color with `font_color_same_lap`, `font_color_laps_ahead`, `font_color_laps_behind` options.

**Comment by srlemke** [comment]
This seems to be fully implemented them, thanks!
