### ISSUE TITLE
Linux - Dark theme support

### ISSUE THREAD

**Issue by alexbrrsclnt** [s-victor/TinyPedal#29]
The app works fine if a light theme is set by default, but when a dark theme is set, the background of the views don't respect the theme and keep the white color, while fonts change from black to white, making very difficult to read. The preset view is readable because of the red background of the default/selected row.

![tinipedal_dark_theme_widget](https://github.com/s-victor/TinyPedal/assets/3874295/e4aef8cb-843c-45e3-b8fd-ae4c88920043)
![tinipedal_dark_theme_module](https://github.com/s-victor/TinyPedal/assets/3874295/2ecb8870-a32b-410c-a34b-7ad903554abc)
![tinipedal_dark_theme_preset](https://github.com/s-victor/TinyPedal/assets/3874295/c9016b1d-2813-4cad-a4be-ddd191cdd587)

Thanks for the app!

**Comment by s-victor** [comment]
Thanks, I'll see what I do to make theme more compatible with different light/dark mode.

**Comment by s-victor** [comment]
ok, this issue should be fixed in latest commits.

**Comment by alexbrrsclnt** [comment]
With latest changes now seems fine!

Thanks!
