### ISSUE TITLE
[RFE] add some session info to either timing or relative

### ISSUE THREAD

**Issue by thoraxe** [s-victor/TinyPedal#3]
It would be nice to have some of the session info available -- current lap vs. max laps, time left in session, etc.

Some of these are inspiration:
https://www.racedepartment.com/downloads/rf2-simhub-mmo-modern-multiclass-overlay-standings-relative-tires.45898/

I can try to work on some of this if you are interested.

**Comment by s-victor** [comment]
Sure, you can find `time_left` in readapi.py under timing() function, as well as `sec2sessiontime` function in calculation.py, which I was initially used it to display session timer in timing widget, but later on I felt it should be placed in its own widget, but haven't got time to do it. So I think you can use those to create `time left` session info in a separate new widget.

Besides your mentioned session info (laps/max laps, etc), it may also be nice to include an optional player's local clock time, to help player knew which time is it easier.

Feel free to add features as you thought suitable, and thanks for help.

**Comment by thoraxe** [comment]
OK, I will try to build some kind of time/laps widget.

**Comment by s-victor** [comment]
Hi, [v1.2.0](https://github.com/s-victor/TinyPedal/releases/tag/v1.2.0) update has added new Session widget with all the info mentioned. This issue will be closed now.
