### ISSUE TITLE
[Feature/Sugestion] "Auto" tyre and breake heatmaps

### ISSUE THREAD

**Issue by Sasker** [s-victor/TinyPedal#39]
How about adding a "heatmap_auto" option to the heatmap related widgets to try to automatically set heatmaps for the class car?
I think that could be a useful addition, because changing the heatmap option every time you race another mod can be forgettable and slow.

I was thinking of extending the classes.json functionality to add autoheatmap and autobrakemap to each known class and then use this (if available) to change the heatmap dynamically.

For example, from this:
`    "LMP1": {
        "LMP1": "#FF00AA"
    },
    "GT3": {
        "GT3": "#229900"
    },`
to this:
`    "LMP1": {
        "LMP1": {
			"color":"#FF00AA",
			"autotyreheatmap":"tyre_optimal_90",
			"autobrakemap":"brake_optimal_700"
		}
    },
    "GT3": {
        "GT3": {
			"color":"#229900",
			"autotyreheatmap":"tyre_optimal_70",
			"autobrakemap":"brake_optimal_400"
		}
    },`

Yes, I know, this will only be useful if we add the most popular mods and theoretical heatmaps.

I can code it in my fork if you believe in it.
(Sorry for my english)

**Comment by s-victor** [comment]
Thank you for your suggestion.

However there is already the preset manager where you can duplicate a single preset (by right click on a preset in preset list to bring up context menu) with preferred overlay setting to create multiple copies and assign different heatmaps to them. And this way you can name preset differently for different cars/events/race types as you wish, which is more simple & flexible.

So currently there is no reason to add additional auto selection function to heatmap or other similar stuff.

**Comment by Sasker** [comment]
Ok.

But you can't assign a preset directly/auto to cars/tracks, so you need to change manually.

Understood

**Comment by s-victor** [comment]
Update: Tyre heatmap auto-matching is now implemented here https://github.com/s-victor/TinyPedal/commit/d704c635a179a2681ec73c2f59ae51465bc67fa0 , and released in https://github.com/s-victor/TinyPedal/releases/tag/v2.24.0
