### ISSUE TITLE
Does not always show up when going into Drive mode

### ISSUE THREAD

**Issue by curVV** [s-victor/TinyPedal#4]
In a 2 hour session (current rf2 competition system) the widgets fail to show up on around 2 or 3 occasions, after clicking Drive. I have to go back to garage a couple of times before it shows up again.

Using latest Shared Memory Map Plugin and TinyPedal 1.6.6.
Other applications in use: CrewChief, FanaLEDs

**Comment by s-victor** [comment]
Hi, thanks for reporting. Can you check *.log file under TinyPedal root folder, if there is any, please post its content here. 

If there is no log file found, it is possible something issue with sharememory plugin. As in very rare case, sharememory plugin can malfunction and become unresponsive, and TinyPedal could fail to read info update which leads to issues like this.
Note: the current auto-hide logic is determined by driver's car ignition status (on/off).
