### ISSUE TITLE
Plugin/download link not quite working

### ISSUE THREAD

**Issue by thoraxe** [s-victor/TinyPedal#43]
The link to download TheIronWolf's plugin doesn't quite work. It takes you to the right thread on the S397 forum, but the original post links to a download that is broken.

Far down in that thread, you find a link to a newer version of the download:
https://www.mediafire.com/file/s6ojcr9zrs6q9ls/rf2_sm_tools_3.7.15.1.zip/file

You might want to link directly to this. However, doing so is fragile. If this link changes or is removed, we'll be in the same boat.

Is there a reason to not do your own build of the tools?

**Comment by s-victor** [comment]
Thanks for the heads up, download link is update here https://github.com/s-victor/TinyPedal/commit/a8a6bc560d9d02fb9c157a648881e755113f3e3b
The new link is from plugin's github page, so I guess it will be safer and less confusion.

By the way, it is not necessary to use latest plugin to access new features from API, old 3.7.14 still works with all new stuff.
