### ISSUE TITLE
Track Time on Cruise widget does not follow time acceleration

### ISSUE THREAD

**Issue by srlemke** [s-victor/TinyPedal#44]
Recently I did the 2.4h of Le Mans race on LMU, that race had the time accelerated by 10x to reflect a 24h event.

I noticed the Track Time on Cruise widget could not follow the track time, it followed real time. Dunno if this is a TP bug or a limitation on the API.

thanks!

**Comment by s-victor** [comment]
hi, just want to inform you that auto synchronizing "time scale" was now finally implemented in https://github.com/s-victor/TinyPedal/commit/ff3b63ccf5ec77743c96146e04dd5ce6e8833bf4 by accessing game's Rest API data.
