### ISSUE TITLE
LMU crashes 

### ISSUE THREAD

**Issue by eliteangler** [s-victor/TinyPedal#48]
After installing TinyPedal and the LMU Custom Plugin Variables files to the correct folders, LMU crashes to desktop.  Please see the attached screenshots.  The edited "CustomPluginVariables" JSON file which is in LMU/User Data/Player folder, and the new plugin for the rFactor2SharedMemory file which is in the LMU/Plugins folder.  Maybe today's patch with the game has made this version not work?  Please advise.  

Thanks!

**Comment by s-victor** [comment]
Hello, `rFactor2SharedMemory Plugin` was tested and working correctly in latest LMU update (Patch #2 - 26th March 2024). The crash may not be resulted by the plugin.

Note, TinyPedal app only reads memory data that sent by `rFactor2SharedMemory` plugin, it does not interact with the game. If there are any issues with game crash, you may consider to report crash issue to LMU game forum, or plugin's [github page](https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin) if it is a plugin issue.

**Comment by s-victor** [comment]
Hello, `rFactor2SharedMemory Plugin` was tested and working correctly in latest LMU update from 26th March 2024. The crash may not be resulted by the plugin.

Note, TinyPedal app only reads memory data that sent by `rFactor2SharedMemory` plugin, it does not directly interact with the game. If there are any issues with game crash, you may consider to report crash issue to LMU game forum, or plugin's [github page](https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin) or [plugin's thread](https://forum.studio-397.com/index.php?threads/rf2-shared-memory-tools-for-developers.54282/) if it is a plugin issue.
