### ISSUE TITLE
Widget positions are messed up when using multi monitor profiles

### ISSUE THREAD

**Issue by Moartl31** [s-victor/TinyPedal#5]
I've got 5 monitors in total connected to my PC. In order to have not all of them active at the same time I'm using the tool "Monitor Profile Switcher". In this way I can activate the Monitors on my Rig using a Hotkey. All other monitors (like on the desc) will then be disabled. Since TinyPedal is in AutoStart it is running with different Monitor Configurations. I think this is the reason why the widget positions are messed up every time.

It would help if the positions could be saved depending on the currently active monitor.

**Comment by s-victor** [comment]
Hi, thanks for the feedback. Currently I'm not sure if it is possible with the GUI software the APP uses. I will try seek solutions.

Regards

**Comment by Moartl31** [comment]
Any updates on this issue?

An idea would be maybe to add an additional option if activated the X, Y positions of widgets are locked and they no longer try to adjust to the monitor size so that they are within the visible area.

I tried to make a write protection on the whole config file however as there are values that need to be constantly changed during runtime so that certain widgets function as intended this is not a solution of course.

Another approach would be to split the config files into two parts. One file just contains the configuration which values are never changed during normal use and a second file that holds all changing values. In this way it would be possible to protect the config file by adding a write protection in order to make sure that nothing gets changed.

**Comment by s-victor** [comment]
Hi, thanks for asking. I believe the core issue is not about config file, but somehow the real screen position gets changed after restart APP, and saved APP position setting from previous session does not match the new screen info that APP sees.

Unfortunately I don't have multi-screen, and the GUI library doesn't provide screen identify info, nor supports direct position change according to screen ID. So this will not be possible to fix without help from someone with multi-screen.

If you or anyone would like to help, there is a few things I could use some info:
1) how many screens you have, the entire desktop resolution combined, and the screen (with ID) order (from left to right).
2) on which screen ID have you started APP, and if you start APP from another screen, will the position be different.
3) record a widget x,y position value from config file before and after start APP, and after closing APP record it again. Also if the position changes when start app from a different screen(as in second question), also record x,y position value. And post those values here.
