### ISSUE TITLE
Engine oil/water temperature not reading correctly on S397 AMG GT3

### ISSUE THREAD

**Issue by thoraxe** [s-victor/TinyPedal#51]
It appears that the TinyPedal display of engine oil and water temperature is locked at 32, but the dash on the vehicle is showing changing oil and water temperature. I've not checked any other cars to see if this issue persists.

**Comment by s-victor** [comment]
GTE and GT3 official DLCs all have engine temperature(oil & water) data output disabled by game API, so it always return 0 degree in Celsius, which equals 32 in Fahrenheit.

**Comment by thoraxe** [comment]
Ah, I had a suspicion. Thanks!
