### ISSUE TITLE
liters per lap

### ISSUE THREAD

**Issue by fralbo** [s-victor/TinyPedal#52]
Hello,
Could you please add "liters per lap" info in maybe Engine widget?

**Comment by s-victor** [comment]
hi,

Are there any reasons that you would want to have this "fuel consumption per lap" data included in Engine widget?

Since there are already multiple widgets that provide fuel consumption data, such as Fuel widget, Lap time history widget, and Stint history widget.

**Comment by fralbo** [comment]
Hello,
Thanks for the tip, I have to better check the already provided information.
Sorry.
