### ISSUE TITLE
Feature suggestion - detect game & auto apply preset

### ISSUE THREAD

**Issue by naturale0** [s-victor/TinyPedal#58]
Just wanted to say thanks for the awesome software. It's made racing in rF2 and LMU a lot more fun.

I have a feature suggestion. Could TinyPedal automatically detect when I start rF2 or LMU and load a preset for that specific game? The default HUDs for rF2 and LMU are different, so having presets auto-applied for each would be awesome.

In addition, I really like this project and want to help out. Is there a way to donate?

**Comment by s-victor** [comment]
Thanks for your support and suggestion. It should be possible, I'll add it in to-do list for now, currently there are other stuff in the work, so it probably won't happen any time soon.

There is no need for donation, please don't worry about it, just have fun.

**Comment by s-victor** [comment]
Here is the first implementation of `global user config` https://github.com/s-victor/TinyPedal/commit/88fc6428bf2c5d3c312a153db9fa7546c95806e1, and `auto load preset` is now integrated with overlay control. On windows, the global user config file is saved in `AppData\Roaming\TinyPedal\config.json`.

I'm currently working on adding new dialog and UI controls to allow changing `global user config`, this will take some time. Meanwhile, you can manually open config.json to set `enable_auto_load_preset` to `true`, and `primary_preset` to desired name, then restart APP to take effect.

More later.

**Comment by s-victor** [comment]
Just added initial implementation for toggling "Auto load preset" system, and managing/tagging primary preset for auto loading in this commit https://github.com/s-victor/TinyPedal/commit/250d0a21424b3352d8f36036a6eb6c7c00e5a951.

The tags can also be applied to multiple games. You can find description in changelog.txt, there will probably be more changes to come later.

Here is how it looks like:
![preset_tagging](https://github.com/user-attachments/assets/864174c0-98d1-4d8b-8bd1-afb23fffddd3)

**Comment by naturale0** [comment]
The UI looks intuitive. Amazing work.

Btw I'd prefer `full name + username`. Thanks for reviewing and merging the pull request so quickly @s-victor !

**Comment by s-victor** [comment]
Thanks, just added you to contributors list. If there are further issues let me know.
