### ISSUE TITLE
Linux Release

### ISSUE THREAD

**Issue by windmill31** [s-victor/TinyPedal#6]
Hi, can TinyPedal be run on Linux ? On the paper, python allows it, but it fails when running it from source (icon.ico is not supported and in the mmap function, the "tagname" parameter is not supported apparently). I'm not a developer so I couldn't solve this.
There's no overlay available on this os, TinyPedal seems to be the only project.
Regards

**Comment by s-victor** [comment]
Hi, while most code of TinyPedal is cross platform, however a few core components do not. One of the affected component is game sharedmemory accessing, which is meant to read memory stuff on windows only. Other stuff includes tray icon functions, transparent windows, etc. So it may not be possible to support linux natively. Hope helps.
