### ISSUE TITLE
Track map implementation request

### ISSUE THREAD

**Issue by AndreT990** [s-victor/TinyPedal#65]
I would like to request if it would be possible to implement in the circuit map the ability to see cars of different categories displayed with separate colors (e.g., LMH hypercars, LMGTE, and LMP2). It would also be useful to show the positions for the separate standings.
Thank you for your work.

**Comment by s-victor** [comment]
thanks, I'll add it to todo list.

**Comment by s-victor** [comment]
Multi-class styling & position in class options are now implemented for Track map Widget here: https://github.com/s-victor/TinyPedal/commit/033c570892384298a86018091114447d7cdccea1

![multiclass_style](https://github.com/user-attachments/assets/00e4fafc-7866-4fd4-88cc-22dcaf3b26f3)

**Comment by AndreT990** [comment]
Thank you very much! Can’t wait to try it out.
