### ISSUE TITLE
[Feature Request] Add pitcount to relatives

### ISSUE THREAD

**Issue by srlemke** [s-victor/TinyPedal#8]
Would it be possible to have the option to show the pitcount of my oponents on the relatives overlay?
Currently we have show_pit_status but this one only shows while the car is in the pits.

Another thing that I think could be helpfull would be the option to show also the car name, this can also help on the strategy as some cars may have more or less tire wear || fuel consumption, knowing that may also help in defining a strategy.

I had a look on the SM and seem that both info is provided.

thanks!

**Comment by s-victor** [comment]
Hi, thanks for suggestion, will try add it in future update.

**Comment by s-victor** [comment]
hello, the pitstop count & vehicle name display features have just been added in following commits:
https://github.com/s-victor/TinyPedal/commit/c31c2eda9f58a53f9a110a23d7b8c64a7ce068c7
https://github.com/s-victor/TinyPedal/commit/e80b217cdd09722afa754b5434b88f03d6c22d60
